games = [
    {
        "id": 14,
        "cover": {
            "id": 234031,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co50kv.jpg",
        },
        "first_release_date": 909619200,
        "genres": [
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 16, "name": "Turn-based strategy (TBS)"},
        ],
        "involved_companies": [
            {"id": 4152, "company": {"id": 12, "name": "Black Isle Studios"}},
            {"id": 4153, "company": {"id": 5, "name": "Interplay Entertainment"}},
        ],
        "name": "Fallout 2",
        "similar_games": [
            {"id": 13, "name": "Fallout"},
            {"id": 15, "name": "Fallout 3"},
            {"id": 16, "name": "Fallout: New Vegas"},
            {"id": 41, "name": "Deus Ex"},
            {"id": 533, "name": "Dishonored"},
            {"id": 832, "name": "Planescape: Torment"},
            {"id": 1020, "name": "Grand Theft Auto V"},
            {"id": 2031, "name": "Wolfenstein: The New Order"},
            {"id": 9498, "name": "Deus Ex: Mankind Divided"},
            {"id": 9630, "name": "Fallout 4"},
        ],
        "summary": "A turn-based tactical Western RPG in which the Chosen One is tasked with exploring post-nuclear California to locate and retrieve the fabled Garden of Eden Creation Kit for their famine-stricken tribe, while coming into contact through branching dialogue trees with numerous tribes, factions and micro-civilizations, each with their own virtues, vices, socioeconomic situations and political agendas.",
        "total_rating": 90.714739825283,
    },
    {
        "id": 23,
        "cover": {
            "id": 204916,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co4e44.jpg",
        },
        "first_release_date": 780192000,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 12, "name": "Role-playing (RPG)"},
        ],
        "involved_companies": [
            {"id": 754, "company": {"id": 3, "name": "Looking Glass Studios"}},
            {"id": 755, "company": {"id": 295, "name": "Origin Systems"}},
        ],
        "name": "System Shock",
        "similar_games": [
            {"id": 673, "name": "DOOM"},
            {"id": 1006, "name": "Syndicate"},
            {"id": 1877, "name": "Cyberpunk 2077"},
            {"id": 11646, "name": "Ziggurat"},
            {"id": 17447, "name": "Titanfall 2"},
            {"id": 19531, "name": "Prey"},
            {"id": 55038, "name": "Immortal: Unchained"},
            {"id": 103281, "name": "Halo Infinite"},
            {"id": 105049, "name": "Remnant: From the Ashes"},
            {"id": 105269, "name": "Gene Rain"},
        ],
        "summary": "A seminal cyberpunk first-person exploratory adventure game with RPG elements in which, waking up in the Citadel Space Station, a lone hacker has to survive corrupted enemies and collect audio logs and equipment from former station workers in order to shut down SHODAN, the station's artificial intelligence that has killed everyone on board and now intends to destroy the world.",
        "total_rating": 91.1138069755641,
    },
    {
        "id": 61,
        "cover": {
            "id": 141219,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co30yr.jpg",
        },
        "first_release_date": 691545600,
        "genres": [
            {"id": 2, "name": "Point-and-click"},
            {"id": 9, "name": "Puzzle"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 7101, "company": {"id": 10, "name": "LucasArts"}}
        ],
        "name": "Monkey Island 2: LeChuck's Revenge",
        "similar_games": [
            {"id": 60, "name": "The Secret of Monkey Island"},
            {"id": 13189, "name": "Masochisia"},
            {"id": 18011, "name": "Rusty Lake Hotel"},
            {"id": 20342, "name": "Toby: The Secret Mine"},
            {"id": 25222, "name": "Rusty Lake: Roots"},
            {"id": 25646, "name": "Don't Knock Twice"},
            {"id": 27725, "name": "The Room: Old Sins"},
            {"id": 28309, "name": "Tanzia"},
            {"id": 81275, "name": "Unforeseen Incidents"},
            {"id": 105049, "name": "Remnant: From the Ashes"},
        ],
        "summary": "Wannabe pirate Guybrush Threepwood, and the now zombie pirate LeChuck, return in what has long been considered one of the greatest LucasArts adventure games of all time.\n\nHaving seemingly defeated the evil ghost pirate LeChuck in his first adventure, Guybrush Threepwood sets his sights on the legendary treasure of Big Whoop. But wait, LeChuck is now back in zombie form and he's out for revenge. Guybrush will have to use his wits, his humor and his insatiable desire for adventure to defeat his nemesis once and for all and truly prove himself the greatest pirate in the Caribbean. Voodoo dolls, spitting contests and amusement parks are just some of the challenges Guybrush must overcome as he meets old friends, fights new enemies and uses every ounce of his mojo to overcome the wrath of LeChuck's revenge.",
        "total_rating": 90.0885966176755,
    },
    {
        "id": 68,
        "cover": {
            "id": 113382,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2fhi.jpg",
        },
        "first_release_date": 846720000,
        "genres": [
            {"id": 15, "name": "Strategy"},
            {"id": 16, "name": "Turn-based strategy (TBS)"},
        ],
        "involved_companies": [
            {"id": 3536, "company": {"id": 151, "name": "Simtex"}},
            {"id": 27094, "company": {"id": 152, "name": "MicroProse"}},
            {"id": 27095, "company": {"id": 130, "name": "MacSoft Games"}},
        ],
        "name": "Master of Orion II: Battle at Antares",
        "similar_games": [
            {"id": 902, "name": "Sid Meier's Civilization"},
            {"id": 8714, "name": "Sid Meier's Starships"},
            {"id": 11550, "name": "Endless Space 2"},
            {"id": 13196, "name": "Tears of Avia"},
            {"id": 13660, "name": "StarDrive 2"},
            {"id": 16806, "name": "Distant Worlds: Universe"},
            {"id": 17111, "name": "Imagine Earth"},
            {"id": 36258, "name": "Order of Battle: World War II"},
            {"id": 102057, "name": "Age of Wonders: Planetfall"},
            {"id": 117417, "name": "Clans to Kingdoms"},
        ],
        "summary": "Master of Orion 2 also known as MOO2 is considered the classic 4x turn based strategy game set in space. The game has a kind of cult status and even by to days standards is still only matched in game play by very few of its competitors.",
        "total_rating": 90.4863564610467,
    },
    {
        "id": 72,
        "cover": {
            "id": 82660,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1rs4.jpg",
        },
        "first_release_date": 1303171200,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 8, "name": "Platform"},
            {"id": 9, "name": "Puzzle"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 106733, "company": {"id": 56, "name": "Valve Corporation"}},
            {"id": 106734, "company": {"id": 1, "name": "Electronic Arts"}},
        ],
        "name": "Portal 2",
        "similar_games": [
            {"id": 71, "name": "Portal"},
            {"id": 1877, "name": "Cyberpunk 2077"},
            {"id": 7350, "name": "Get Even"},
            {"id": 11646, "name": "Ziggurat"},
            {"id": 16992, "name": "Human: Fall Flat"},
            {"id": 22387, "name": "Legrand Legacy"},
            {"id": 28070, "name": "Planet Alpha"},
            {"id": 55038, "name": "Immortal: Unchained"},
            {"id": 55190, "name": "Pikuniku"},
            {"id": 56033, "name": "Dream Alone"},
        ],
        "summary": "Sequel to the acclaimed Portal (2007), Portal 2 pits the protagonist of the original game, Chell, and her new robot friend, Wheatley, against more puzzles conceived by GLaDOS, an A.I. with the sole purpose of testing the Portal Gun's mechanics and taking revenge on Chell for the events of Portal. As a result of several interactions and revelations, Chell once again pushes to escape Aperture Science Labs.",
        "total_rating": 92.06731080431945,
    },
    {
        "id": 74,
        "cover": {
            "id": 93684,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co20ac.jpg",
        },
        "first_release_date": 1264464000,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 13, "name": "Simulator"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 5240, "company": {"id": 2, "name": "BioWare"}},
            {"id": 5241, "company": {"id": 1, "name": "Electronic Arts"}},
            {"id": 18482, "company": {"id": 222, "name": "BioWare Edmonton"}},
            {"id": 52062, "company": {"id": 3903, "name": "BioWare Montréal"}},
        ],
        "name": "Mass Effect 2",
        "similar_games": [
            {"id": 16, "name": "Fallout: New Vegas"},
            {"id": 21, "name": "BioShock 2"},
            {"id": 41, "name": "Deus Ex"},
            {"id": 43, "name": "Deus Ex: Human Revolution"},
            {"id": 533, "name": "Dishonored"},
            {"id": 571, "name": "Singularity"},
            {"id": 960, "name": "Max Payne 3"},
            {"id": 1020, "name": "Grand Theft Auto V"},
            {"id": 1985, "name": "Metal Gear Solid V: The Phantom Pain"},
            {"id": 2031, "name": "Wolfenstein: The New Order"},
        ],
        "summary": "Are you prepared to lose everything to save the galaxy? You'll need to be, Commander Shephard. It's time to bring together your greatest allies and recruit the galaxy's fighting elite to continue the resistance against the invading Reapers. So steel yourself, because this is an astronomical mission where sacrifices must be made. You'll face tougher choices and new, deadlier enemies. Arm yourself and prepare for an unforgettable intergalactic adventure.\n\nGame Features:\n\nShift the fight in your favour. Equip yourself with powerful new weapons almost instantly thanks to a new inventory system. Plus, an improved health regeneration system means you'll spend less time hunting for restorative items.\n\nMake every decision matter. Divisive crew members are just the tip of the iceberg, Commander, because you'll also be tasked with issues of intergalactic diplomacy. And time's a wastin' so don't be afraid to use new prompt-based actions that let you interrupt conversations, even if they could alter the fate of your crew...and the galaxy.\n\nForge new alliances, carefully. You'll fight alongside some of your most trustworthy crew members, but you'll also get the opportunity to recruit new talent. Just choose your new partners with care because the fate of the galaxy rests on your shoulders, Commander.",
        "total_rating": 93.52381411614854,
    },
    {
        "id": 116,
        "cover": {
            "id": 85067,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1tmz.jpg",
        },
        "first_release_date": 1058227200,
        "genres": [
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 18949, "company": {"id": 2, "name": "BioWare"}},
            {"id": 18950, "company": {"id": 10, "name": "LucasArts"}},
            {"id": 18951, "company": {"id": 66, "name": "Activision"}},
            {"id": 150347, "company": {"id": 73, "name": "Aspyr Media"}},
        ],
        "name": "Star Wars: Knights of the Old Republic",
        "similar_games": [
            {"id": 6, "name": "Baldur's Gate II: Shadows of Amn"},
            {"id": 41, "name": "Deus Ex"},
            {"id": 74, "name": "Mass Effect 2"},
            {
                "id": 118,
                "name": "Star Wars: Knights of the Old Republic II - The Sith Lords",
            },
            {"id": 832, "name": "Planescape: Torment"},
            {"id": 1593, "name": "Pillars of Eternity"},
            {"id": 2031, "name": "Wolfenstein: The New Order"},
            {"id": 9927, "name": "Persona 5"},
            {"id": 11292, "name": "Rogue Galaxy"},
            {"id": 26401, "name": "Star Wars Battlefront II"},
        ],
        "summary": "Choose Your Path! Set 4,000 years before the Galactic Empire, you are the last hope for the Jedi Order and the Republic - can you master the ways of the Force to become their savior? Or will you fall to the dark side and achieve ultimate power? Hero, villain, peacekeeper, or chaos-bringer... you and your party will determine the fate of the galaxy!\n\nStar Wars: Knights of the Old Republic is a role-playing video game. Players will be able to create their own characters and be able to choose what gender, appearance, class, skills, attributes, and feats they have throughout the game - no two characters will be the same!",
        "total_rating": 92.46120231575435,
    },
    {
        "id": 132,
        "cover": {
            "id": 90530,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1xuq.jpg",
        },
        "first_release_date": 1025654400,
        "genres": [
            {"id": 11, "name": "Real Time Strategy (RTS)"},
            {"id": 15, "name": "Strategy"},
        ],
        "involved_companies": [
            {"id": 8012, "company": {"id": 51, "name": "Blizzard Entertainment"}},
            {"id": 19472, "company": {"id": 24, "name": "Sierra Entertainment"}},
            {"id": 19473, "company": {"id": 37, "name": "Capcom"}},
        ],
        "name": "Warcraft III: Reign of Chaos",
        "similar_games": [
            {"id": 2365, "name": "Battle for Wesnoth"},
            {"id": 6985, "name": "Three Kingdoms: Fate of the Dragon"},
            {"id": 7027, "name": "SpellForce: The Order of Dawn"},
            {"id": 8773, "name": "Homeworld: Remastered Collection"},
            {"id": 9058, "name": "Praetorians"},
            {"id": 24834, "name": "Trollskog"},
            {"id": 26845, "name": "Fire Emblem: Three Houses"},
            {"id": 30229, "name": "Bannermen"},
            {"id": 55029, "name": "Age of Empires IV"},
            {"id": 78550, "name": "Bad North"},
        ],
        "summary": "Warcraft 3: Reign of Chaos is an RTS made by Blizzard Entertainment. Take control of either the Humans, the Orcs, the Night Elves or the Undead, all with different unit types and heroes with unique abilities.Play the story driven single player campaign, go online to play default- or custom maps against people around the world or create your own maps with the map creation tool.",
        "total_rating": 90.79983263457319,
    },
    {
        "id": 184,
        "cover": {
            "id": 84975,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1tkf.jpg",
        },
        "first_release_date": 707356800,
        "genres": [
            {"id": 2, "name": "Point-and-click"},
            {"id": 9, "name": "Puzzle"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 108300, "company": {"id": 227, "name": "U.S. Gold"}},
            {"id": 112605, "company": {"id": 10, "name": "LucasArts"}},
            {"id": 112606, "company": {"id": 95, "name": "Disney Interactive"}},
        ],
        "name": "Indiana Jones and the Fate of Atlantis",
        "similar_games": [
            {"id": 62, "name": "The Curse of Monkey Island"},
            {
                "id": 186,
                "name": "Indiana Jones and the Last Crusade: The Graphic Adventure",
            },
            {"id": 189, "name": "LEGO Indiana Jones: The Original Adventures"},
            {"id": 191, "name": "Loom"},
            {"id": 616, "name": "Circle of Blood"},
            {"id": 2935, "name": "Papers, Please"},
            {"id": 9835, "name": "Draugen"},
            {"id": 18841, "name": "Gibbous - A Cthulhu Adventure"},
            {"id": 24426, "name": "Forgotton Anne"},
            {"id": 55984, "name": "Blacksad: Under the Skin"},
        ],
        "summary": 'A point-and-click adventure game by LucasArts originally released in 1992. Almost a year later, it was reissued on CD-ROM as an enhanced "talkie" edition with full voice acting and digitized sound effects. In 2009, this version was also released as an unlockable extra of the Wii action game Indiana Jones and the Staff of Kings, and as a digitally distributed Steam title. The seventh game to use the script language SCUMM, Fate of Atlantis has the player explore environments and interact with objects and characters by using commands constructed with predetermined verbs. It features three unique paths to select, influencing story development, gameplay and puzzles.',
        "total_rating": 90.03545799488879,
    },
    {
        "id": 193,
        "cover": {
            "id": 141221,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co30yt.jpg",
        },
        "first_release_date": 740966400,
        "genres": [
            {"id": 2, "name": "Point-and-click"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [{"id": 786, "company": {"id": 10, "name": "LucasArts"}}],
        "name": "Day of the Tentacle",
        "similar_games": [
            {"id": 533, "name": "Dishonored"},
            {"id": 538, "name": "BioShock Infinite"},
            {"id": 1906, "name": "Gone Home"},
            {"id": 2031, "name": "Wolfenstein: The New Order"},
            {"id": 2939, "name": "The Vanishing of Ethan Carter"},
            {"id": 2993, "name": "The Wolf Among Us"},
            {"id": 3087, "name": "Broken Age"},
            {"id": 3188, "name": "Murdered: Soul Suspect"},
            {"id": 9727, "name": "SOMA"},
            {"id": 11270, "name": "The Cat Lady"},
        ],
        "summary": "Day of the Tentacle, also known as Maniac Mansion II: Day of the Tentacle, is a 1993 graphic adventure game developed and published by LucasArts. It is the sequel to the 1987 game Maniac Mansion. The game's plot follows Bernard Bernoulli and his friends Hoagie and Laverne as they attempt to stop the evil Purple Tentacle — a sentient, disembodied tentacle — from taking over the world. The player takes control of the three and solves puzzles while using time travel to explore different periods of history.\n\nDave Grossman and Tim Schafer co-led the game's development, their first time in such a role. The pair carried over a limited amount of elements from Maniac Mansion and forwent the character selection aspect to simplify development. Inspirations included Chuck Jones cartoons and the history of the United States. Day of the Tentacle is the eighth LucasArts title to use the SCUMM engine, and the company's first title to feature voice acting.\n\nThe game was released simultaneously on floppy disk and CD-ROM to critical acclaim and commercial success. Critics focused on its cartoon-style visuals and comedic elements. Day of the Tentacle has featured regularly in lists of \"top\" games published more than two decades after its release, and aspects have been referenced in popular culture.",
        "total_rating": 90.9375140955661,
    },
    {
        "id": 228,
        "cover": {
            "id": 90549,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1xv9.jpg",
        },
        "first_release_date": 1226534400,
        "genres": [{"id": 12, "name": "Role-playing (RPG)"}],
        "involved_companies": [
            {"id": 7675, "company": {"id": 51, "name": "Blizzard Entertainment"}}
        ],
        "name": "World of Warcraft: Wrath of the Lich King",
        "similar_games": [
            {"id": 16391, "name": "ROSE Online"},
            {"id": 19404, "name": "Eador: Imperium"},
            {"id": 19698, "name": "Albion Online"},
            {"id": 23651, "name": "Echo of Soul"},
            {"id": 27092, "name": "GreedFall"},
            {"id": 36198, "name": "Children of Morta"},
            {"id": 47823, "name": "Citadel: Forged With Fire"},
            {"id": 54775, "name": "Shadows: Awakening"},
            {"id": 55199, "name": "Dragon: Marked for Death"},
            {"id": 59427, "name": "Fairy Tail Online"},
        ],
        "summary": 'World of Warcraft: Wrath of the Lich King, often referred to as WotLK, or Wrath, is the second expansion set for the massively multiplayer online role-playing game (MMORPG) World of Warcraft, following The Burning Crusade. It adds a substantial amount of content to the game world, including the continent of Northrend, home of the eponymous Lich King, and a new character "hero" class.',
        "total_rating": 93.4785292628307,
    },
    {
        "id": 233,
        "cover": {
            "id": 77288,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1nmw.jpg",
        },
        "first_release_date": 1100563200,
        "genres": [{"id": 5, "name": "Shooter"}],
        "involved_companies": [
            {"id": 18928, "company": {"id": 24, "name": "Sierra Entertainment"}},
            {"id": 18929, "company": {"id": 56, "name": "Valve Corporation"}},
            {
                "id": 88970,
                "company": {"id": 22994, "name": "NVIDIA Lightspeed Studios"},
            },
        ],
        "name": "Half-Life 2",
        "similar_games": [
            {"id": 231, "name": "Half-Life"},
            {"id": 471, "name": "Crysis 2"},
            {"id": 571, "name": "Singularity"},
            {"id": 673, "name": "DOOM"},
            {"id": 1011, "name": "Borderlands 2"},
            {"id": 7350, "name": "Get Even"},
            {"id": 15536, "name": "Escape from Tarkov"},
            {"id": 37016, "name": "Metro Exodus"},
            {"id": 103301, "name": "Wolfenstein: Youngblood"},
            {"id": 113114, "name": "The Outer Worlds"},
        ],
        "summary": "1998. HALF-LIFE sends a shock through the game industry with its combination of pounding action and continuous, immersive storytelling.\n\nNOW. By taking the suspense, challenge and visceral charge of the original, and adding startling new realism and responsiveness, Half-Life 2 opens the door to a world where the player's presence affects everything around them, from the physical environment to the behaviors even the emotions of both friends and enemies.",
        "total_rating": 90.89700797881785,
    },
    {
        "id": 272,
        "cover": {
            "id": 119351,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2k3b.jpg",
        },
        "first_release_date": 943228800,
        "genres": [{"id": 5, "name": "Shooter"}],
        "involved_companies": [
            {"id": 87890, "company": {"id": 17463, "name": "Epic Games"}},
            {"id": 99914, "company": {"id": 17, "name": "Digital Extremes"}},
            {"id": 99915, "company": {"id": 205, "name": "GT Interactive"}},
            {"id": 99916, "company": {"id": 213, "name": "Infogrames"}},
            {"id": 99917, "company": {"id": 130, "name": "MacSoft Games"}},
        ],
        "name": "Unreal Tournament",
        "similar_games": [
            {"id": 10964, "name": "Sniper: Ghost Warrior 3"},
            {"id": 19164, "name": "Borderlands 3"},
            {"id": 28751, "name": "Black Squad"},
            {"id": 54844, "name": "Ion Fury"},
            {"id": 83727, "name": "Call of Duty: Black Ops 4"},
            {"id": 103301, "name": "Wolfenstein: Youngblood"},
            {"id": 105049, "name": "Remnant: From the Ashes"},
            {"id": 105269, "name": "Gene Rain"},
            {"id": 106805, "name": "Call of Duty: Mobile"},
            {"id": 113114, "name": "The Outer Worlds"},
        ],
        "summary": "The first game in the Unreal series which has come to revolutionize game physics in the present. Unreal is a first person shooter with futuristic weapons, ammo, and arenas.",
        "total_rating": 93.09154883583685,
    },
    {
        "id": 293,
        "cover": {
            "id": 82357,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1rjp.jpg",
        },
        "first_release_date": 1130198400,
        "genres": [
            {"id": 13, "name": "Simulator"},
            {"id": 15, "name": "Strategy"},
            {"id": 16, "name": "Turn-based strategy (TBS)"},
        ],
        "involved_companies": [
            {"id": 3526, "company": {"id": 8, "name": "2K Games"}},
            {"id": 3527, "company": {"id": 73, "name": "Aspyr Media"}},
            {"id": 8184, "company": {"id": 377, "name": "Firaxis Games"}},
            {"id": 21720, "company": {"id": 139, "name": "Take-Two Interactive"}},
        ],
        "name": "Sid Meier's Civilization IV",
        "similar_games": [
            {"id": 276, "name": "Supreme Commander"},
            {"id": 310, "name": "Sid Meier's Civilization III"},
            {"id": 438, "name": "Rome: Total War"},
            {"id": 440, "name": "Medieval II: Total War"},
            {"id": 662, "name": "Anno 1404"},
            {"id": 848, "name": "Rise of Nations"},
            {"id": 866, "name": "Sid Meier's Civilization V"},
            {"id": 1904, "name": "Europa Universalis IV"},
            {"id": 2040, "name": "Knights of Honor"},
            {"id": 2918, "name": "Crusader Kings II"},
        ],
        "summary": "Sid Meier and Firaxis Games will take this incredibly fun and addictive game to new heights by adding new ways to play and win, new tools to manage and expand your civilization, all-new easy to use mod capabilities and intense multiplayer modes and options",
        "total_rating": 90.7076104488907,
    },
    {
        "id": 339,
        "cover": {
            "id": 137915,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2yez.jpg",
        },
        "first_release_date": 1191974400,
        "genres": [{"id": 5, "name": "Shooter"}, {"id": 9, "name": "Puzzle"}],
        "involved_companies": [
            {"id": 684, "company": {"id": 56, "name": "Valve Corporation"}},
            {"id": 170786, "company": {"id": 276, "name": "EA UK"}},
        ],
        "name": "The Orange Box",
        "similar_games": [
            {"id": 10603, "name": "Numba Deluxe"},
            {"id": 19222, "name": "Digging Jim"},
            {"id": 25905, "name": "Winds of Revenge"},
            {"id": 40096, "name": "Drakton"},
            {"id": 41349, "name": "Hayama Reiko no Date de Blackjack"},
            {"id": 43453, "name": "Twinkle Star Sprites: La Petite Princesse"},
            {"id": 87507, "name": "Whirly Word HD"},
            {"id": 90788, "name": "Munchkin Match"},
            {"id": 95776, "name": "Turn It On!"},
            {"id": 106992, "name": "A Fisherman's Tale"},
        ],
        "summary": "The Orange Box is a bundle that includes five titles from Valve: Half-Life 2; Half-Life 2:Episode 1; Half-Life 2: Episode Two; Team Fortress 2, the sequel to the game that put class-based, multiplayer team warfare on the map; and Portal, the game that blends puzzles, first person action, and adventure gaming to produce an experience like no other.",
        "total_rating": 90.03056652862784,
    },
    {
        "id": 364,
        "cover": {
            "id": 106423,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2a47.jpg",
        },
        "first_release_date": 920160000,
        "genres": [
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 15, "name": "Strategy"},
            {"id": 16, "name": "Turn-based strategy (TBS)"},
        ],
        "involved_companies": [
            {"id": 19116, "company": {"id": 106, "name": "Loki Software"}},
            {"id": 19117, "company": {"id": 99, "name": "The 3DO Company"}},
            {"id": 19118, "company": {"id": 97, "name": "New World Computing"}},
        ],
        "name": "Heroes of Might and Magic III: The Restoration of Erathia",
        "similar_games": [
            {"id": 363, "name": "Heroes of Might and Magic II: The Succession Wars"},
            {"id": 367, "name": "Heroes of Might and Magic IV"},
            {"id": 370, "name": "Heroes of Might and Magic V"},
            {"id": 373, "name": "Might & Magic: Heroes VI"},
            {"id": 660, "name": "Darkstone"},
            {"id": 1593, "name": "Pillars of Eternity"},
            {"id": 2365, "name": "Battle for Wesnoth"},
            {
                "id": 3155,
                "name": "The Lord of the Rings: The Battle for Middle-earth II",
            },
            {"id": 9834, "name": "Warlords Battlecry III"},
            {"id": 9938, "name": "Aarklash: Legacy"},
        ],
        "summary": "Heroes of Might and Magic III: The Restoration of Erathia is a turn-based strategy game and the third installment of the Heroes of Might and Magic series.\n\nThe game's story is first referenced throughout Might and Magic VI: The Mandate of Heaven and takes place before Might and Magic VII: For Blood and Honor. The player can choose to play through six different campaigns telling the story, or play in a scenario against computer or human opponents.",
        "total_rating": 90.0898929309882,
    },
    {
        "id": 380,
        "cover": {
            "id": 252138,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co5eju.jpg",
        },
        "first_release_date": 1213228800,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 24, "name": "Tactical"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 839, "company": {"id": 170, "name": "Kojima Productions"}},
            {"id": 840, "company": {"id": 129, "name": "Konami"}},
        ],
        "name": "Metal Gear Solid 4: Guns of the Patriots",
        "similar_games": [
            {"id": 41, "name": "Deus Ex"},
            {"id": 296, "name": "Crysis"},
            {"id": 375, "name": "Metal Gear Solid"},
            {"id": 379, "name": "Metal Gear Solid 3: Snake Eater"},
            {"id": 623, "name": "Call of Duty 4: Modern Warfare"},
            {"id": 960, "name": "Max Payne 3"},
            {"id": 1009, "name": "The Last of Us"},
            {"id": 1020, "name": "Grand Theft Auto V"},
            {"id": 1985, "name": "Metal Gear Solid V: The Phantom Pain"},
            {"id": 2031, "name": "Wolfenstein: The New Order"},
        ],
        "summary": "Metal Gear Solid 4: Guns of the Patriots is the final canonical Metal Gear game to feature Solid Snake as the main character. The gameplay of the previous games have been kept along with some new features, such as the ability to roll on your back and also to hide in bins scattered around the environment. Most of the story and the relationship between the characters are explained through cut-scenes with a considerable length, so knowledge of the prior games is recommended to fully understand the story. The game also features a complex multiplayer mode entitled Metal Gear Online with some original missions based on the stealth aspects of the single-player games.",
        "total_rating": 90.5797851090968,
    },
    {
        "id": 418,
        "cover": {
            "id": 85213,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1tr1.jpg",
        },
        "first_release_date": 995500800,
        "genres": [
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 178030, "company": {"id": 252, "name": "Square Electronic Arts"}},
            {"id": 178031, "company": {"id": 250, "name": "Square"}},
        ],
        "name": "Final Fantasy X",
        "similar_games": [
            {"id": 359, "name": "Final Fantasy XV"},
            {"id": 389, "name": "Final Fantasy XIII"},
            {"id": 1802, "name": "Chrono Trigger"},
            {"id": 2365, "name": "Battle for Wesnoth"},
            {"id": 10297, "name": "Fallen Enchantress"},
            {"id": 11292, "name": "Rogue Galaxy"},
            {"id": 14394, "name": "Battle Brothers"},
            {"id": 22387, "name": "Legrand Legacy"},
            {"id": 36198, "name": "Children of Morta"},
            {"id": 55038, "name": "Immortal: Unchained"},
        ],
        "summary": "Final Fantasy X is the tenth main installment in the FF series and the first title released on sixth-generation consoles. It was also the first game to feature fully three-dimensional areas rather than including pre-rendered backdrops, and the first to include voice acting. Final Fantasy X tells the story of a star blitzball player, Tidus, who journeys with a young and beautiful summoner named Yuna on her quest to save the world of Spira from an endless cycle of destruction wrought by the colossal menace Sin.",
        "total_rating": 91.0742994697909,
    },
    {
        "id": 426,
        "cover": {
            "id": 141698,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co31c2.jpg",
        },
        "first_release_date": 765244800,
        "genres": [
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 159793, "company": {"id": 26, "name": "Square Enix"}},
            {
                "id": 164524,
                "company": {"id": 334, "name": "Sony Computer Entertainment Europe"},
            },
            {"id": 165884, "company": {"id": 250, "name": "Square"}},
            {"id": 180322, "company": {"id": 321, "name": "Tose"}},
        ],
        "name": "Final Fantasy VI",
        "similar_games": [
            {"id": 6, "name": "Baldur's Gate II: Shadows of Amn"},
            {"id": 384, "name": "Final Fantasy XIII-2"},
            {"id": 398, "name": "Final Fantasy XII"},
            {"id": 421, "name": "Final Fantasy IX"},
            {"id": 425, "name": "Final Fantasy VIII"},
            {"id": 427, "name": "Final Fantasy VII"},
            {"id": 428, "name": "Final Fantasy Tactics"},
            {"id": 832, "name": "Planescape: Torment"},
            {"id": 1804, "name": "Chrono Cross"},
            {"id": 16474, "name": "Final Fantasy II"},
        ],
        "summary": "Final Fantasy VI is the sixth main installment in the Final Fantasy series, developed and published by Square. It was the final title in the series to feature two-dimensional graphics, and the first story that did not revolve around crystals.\n\nThe game gives players up to fourteen playable characters, the largest cast in the series, and features the Active Time Battle pseudo-turn based menu command system. A party can consist of up to four characters, though some events require the player to assemble three different parties of up to four and switch between them.\n\nEach character has a unique command ability, such as Terra's Trance, Locke's Steal, Edgar's Tools or Sabin's Blitz, and can also learn Magic spells from earning AP from battles with magicite equipped. Each character's rare Desperation Attack will randomly activate after using the Attack command when at critical health.",
        "total_rating": 95.05772953767175,
    },
    {
        "id": 434,
        "cover": {
            "id": 120991,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2lcv.jpg",
        },
        "first_release_date": 1274140800,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 3868, "company": {"id": 29, "name": "Rockstar Games"}},
            {"id": 3869, "company": {"id": 365, "name": "Rockstar North"}},
            {"id": 3870, "company": {"id": 364, "name": "Rockstar San Diego"}},
            {"id": 18530, "company": {"id": 139, "name": "Take-Two Interactive"}},
        ],
        "name": "Red Dead Redemption",
        "similar_games": [
            {"id": 40, "name": "Mafia II"},
            {"id": 109, "name": "L.A. Noire"},
            {"id": 533, "name": "Dishonored"},
            {"id": 564, "name": "Rogue Warrior"},
            {"id": 960, "name": "Max Payne 3"},
            {"id": 1020, "name": "Grand Theft Auto V"},
            {"id": 1121, "name": "Watch_Dogs"},
            {"id": 1164, "name": "Tomb Raider"},
            {"id": 1985, "name": "Metal Gear Solid V: The Phantom Pain"},
            {"id": 19441, "name": "Watch Dogs 2"},
        ],
        "summary": "A modern-day Western epic, Red Dead Redemption takes John Marston, a relic from the fast-closing time of the gunslinger, through an open-world filled with wildlife, mini games and shootouts. Marston sets out to hunt down his old gang mates for the government, who have taken away his family, and meets many characters emblematic of the Wild West, heroism and the new civilization along his journey.",
        "total_rating": 90.61940978244354,
    },
    {
        "id": 472,
        "cover": {
            "id": 85100,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1tnw.jpg",
        },
        "first_release_date": 1320883200,
        "genres": [
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 3719, "company": {"id": 126, "name": "Bethesda Game Studios"}},
            {"id": 95350, "company": {"id": 16565, "name": "Bethesda Softworks"}},
        ],
        "name": "The Elder Scrolls V: Skyrim",
        "similar_games": [
            {"id": 20, "name": "BioShock"},
            {"id": 56, "name": "The Elder Scrolls III: Morrowind"},
            {"id": 59, "name": "The Elder Scrolls IV: Oblivion"},
            {"id": 121, "name": "Minecraft"},
            {"id": 533, "name": "Dishonored"},
            {"id": 538, "name": "BioShock Infinite"},
            {"id": 832, "name": "Planescape: Torment"},
            {"id": 1081, "name": "The Elder Scrolls Online"},
            {"id": 1942, "name": "The Witcher 3: Wild Hunt"},
            {"id": 3025, "name": "Middle-earth: Shadow of Mordor"},
        ],
        "summary": "Skyrim reimagines and revolutionizes the open-world fantasy epic, bringing to life a complete virtual world open for you to explore any way you choose. Play any type of character you can imagine, and do whatever you want; the legendary freedom of choice, storytelling, and adventure of The Elder Scrolls is realized like never before.",
        "total_rating": 91.81913441367166,
    },
    {
        "id": 479,
        "cover": {
            "id": 87306,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1vd6.jpg",
        },
        "first_release_date": 1135209600,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 24, "name": "Tactical"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {
                "id": 836,
                "company": {"id": 312, "name": "Konami Computer Entertainment Japan"},
            },
            {"id": 837, "company": {"id": 170, "name": "Kojima Productions"}},
            {"id": 838, "company": {"id": 129, "name": "Konami"}},
        ],
        "name": "Metal Gear Solid 3: Subsistence",
        "similar_games": [
            {"id": 19164, "name": "Borderlands 3"},
            {"id": 27316, "name": "A Plague Tale: Innocence"},
            {"id": 55038, "name": "Immortal: Unchained"},
            {"id": 81249, "name": "The Elder Scrolls VI"},
            {"id": 96217, "name": "Eternity: The Last Unicorn"},
            {"id": 103210, "name": "HITMAN 2"},
            {"id": 105049, "name": "Remnant: From the Ashes"},
            {"id": 106987, "name": "Torchlight III"},
            {"id": 113360, "name": "Hytale"},
            {"id": 118218, "name": "Tom Clancy's Ghost Recon: Breakpoint"},
        ],
        "summary": "Metal Gear Solid 3: Subsistence continues the Metal Gear Solid series tradition of follow-up enhanced, international version releases. \nSubsistence's online multiplayer component, titled Metal Gear Online, consists of five tournament-style game modes, each with a capacity of up to eight players. This mode pits players, each playing as a generic soldier against each other in deathmatch battles and variations of capture the flag, using stages, items, maneuvers, and units (such as the KGB, GRU or Ocelot Unit) from the main game.",
        "total_rating": 94.89583089831875,
    },
    {
        "id": 481,
        "cover": {
            "id": 134728,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2vyg.jpg",
        },
        "first_release_date": 1001289600,
        "genres": [{"id": 9, "name": "Puzzle"}, {"id": 31, "name": "Adventure"}],
        "involved_companies": [
            {"id": 99380, "company": {"id": 10446, "name": "Team Silent"}},
            {"id": 99381, "company": {"id": 129, "name": "Konami"}},
        ],
        "name": "Silent Hill 2",
        "similar_games": [
            {"id": 480, "name": "Silent Hill"},
            {"id": 482, "name": "Silent Hill 3"},
            {"id": 1009, "name": "The Last of Us"},
            {"id": 1906, "name": "Gone Home"},
            {"id": 2031, "name": "Wolfenstein: The New Order"},
            {"id": 2939, "name": "The Vanishing of Ethan Carter"},
            {"id": 3188, "name": "Murdered: Soul Suspect"},
            {"id": 9727, "name": "SOMA"},
            {"id": 11270, "name": "The Cat Lady"},
            {"id": 19531, "name": "Prey"},
        ],
        "summary": "The second entry in the Silent Hill franchise, Silent Hill 2 is a narrative-focused third-person psychological horror game with exploration and puzzle-solving elements which follows James Sunderland, a man who receives a letter, seemingly sent by his three-years-deceased wife Mary, in which he is beckoned to the fog-ridden town of Silent Hill at the same time as numerous other people troubled by their past.",
        "total_rating": 90.85173773124646,
    },
    {
        "id": 499,
        "cover": {
            "id": 166770,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co3koi.jpg",
        },
        "first_release_date": 1268697600,
        "genres": [
            {"id": 25, "name": "Hack and slash/Beat 'em up"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 45114, "company": {"id": 12303, "name": "Wholesale Algorithms["}},
            {"id": 185862, "company": {"id": 15512, "name": "SCE Santa Monica Studio"}},
            {
                "id": 185863,
                "company": {"id": 13634, "name": "Sony Computer Entertainment"},
            },
        ],
        "name": "God of War III",
        "similar_games": [
            {"id": 127, "name": "Assassin's Creed II"},
            {"id": 533, "name": "Dishonored"},
            {"id": 549, "name": "God of War"},
            {"id": 550, "name": "God of War: Ghost of Sparta"},
            {"id": 551, "name": "God of War II"},
            {"id": 552, "name": "God of War: Chains of Olympus"},
            {"id": 571, "name": "Singularity"},
            {"id": 2031, "name": "Wolfenstein: The New Order"},
            {"id": 3025, "name": "Middle-earth: Shadow of Mordor"},
            {"id": 6958, "name": "Dante's Inferno"},
        ],
        "summary": "Set in the realm of brutal Greek mythology, God of War III is a single-player game that allows players to take on the climatic role of the ex-Spartan warrior, Kratos, as he scales through the intimidating heights of Mt. Olympus and the dark depths of Hell to seek revenge on those who have betrayed him. Armed with double-chained blades, and an array of new weapons and magic for this iteration of the trilogy, Kratos must take on mythology's darkest creatures while solving intricate puzzles throughout his merciless quest to destroy Olympus. Utilizing a new game engine built from the ground up and state-of-the-art visual technologies, the development team behind God of War III has made standard-setting strides in giving players the realistic feel of actually being on the battlegrounds. With texture resolutions quadrupling since God of War II on PlayStation 2 computer entertainment system, God of War III, in its debut on the PS3 system, will feature fluid, life-like characters, as well as dynamic lighting effects, a robust weapon system, and world-changing scenarios that will truly bring unmistakable realism to Kratos' fateful quest. Players will have a chance to join battles on a grand scale that is four times larger than its predecessor.",
        "total_rating": 91.09308716347431,
    },
    {
        "id": 565,
        "cover": {
            "id": 85079,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1tnb.jpg",
        },
        "first_release_date": 1255392000,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 8, "name": "Platform"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 1370, "company": {"id": 401, "name": "Naughty Dog"}},
            {
                "id": 185859,
                "company": {"id": 13634, "name": "Sony Computer Entertainment"},
            },
        ],
        "name": "Uncharted 2: Among Thieves",
        "similar_games": [
            {"id": 128, "name": "Assassin's Creed"},
            {"id": 431, "name": "Uncharted: Drake's Fortune"},
            {"id": 471, "name": "Crysis 2"},
            {"id": 512, "name": "Uncharted 3: Drake's Deception"},
            {"id": 7323, "name": "Rise of the Tomb Raider"},
            {"id": 7331, "name": "Uncharted 4: A Thief's End"},
            {"id": 8263, "name": "Assassin's Creed Syndicate"},
            {"id": 28168, "name": "Code Vein"},
            {"id": 36198, "name": "Children of Morta"},
            {"id": 47823, "name": "Citadel: Forged With Fire"},
        ],
        "summary": "In the sequel to Drake's Fortune, Nathan Drake comes across a map that showcases the location of Marco Polo's missing ships. It takes him on a journey to find the infamous Cintamani Stone, and uncover the truth behind it.",
        "total_rating": 92.38910827248765,
    },
    {
        "id": 600,
        "cover": {
            "id": 560,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/zmaokvadzctygkgessmf.jpg",
        },
        "first_release_date": 807148800,
        "genres": [{"id": 13, "name": "Simulator"}],
        "involved_companies": [
            {"id": 1439, "company": {"id": 467, "name": "Digital Integration"}},
            {"id": 1440, "company": {"id": 467, "name": "Digital Integration"}},
            {"id": 2067, "company": {"id": 466, "name": "Interactive Magic"}},
        ],
        "name": "Apache",
        "similar_games": [
            {"id": 4257, "name": "Flying Nightmares"},
            {"id": 8422, "name": "Breach & Clear"},
            {"id": 12129, "name": "Gunship 2000"},
            {"id": 12929, "name": "Thunderhawk AH-73M"},
            {"id": 14758, "name": "Ace Combat 7: Skies Unknown"},
            {"id": 17130, "name": "Unclaimed World"},
            {"id": 18623, "name": "Villagers"},
            {"id": 20295, "name": "Gunship"},
            {"id": 31515, "name": "Another Brick in the Mall"},
            {"id": 76457, "name": "Digital Combat Simulator: MiG-21Bis Fishbed"},
        ],
        "summary": "You're in command as your AH-64D Apache Longbow combat helicopter lifts off from its forward base. You're going into combat against the best the enemy can offer, but you've got the most advanced fighting helicopter in the world at your fingertips, packed with a devastating array of lethal weapons and state-of-the art technology.\n\nYou're ready to rock and roll but so is the enemy! They're waiting for you with combat helicopters of their own, backed up by radar-guided anti-aircraft guns and missiles and fixed wing aircraft. It's not going to be a cakewalk but you and your Apache are up to the challenge. Across four theaters of war-- Fort Hood where you train and then in war zones in Cyprus, Yemen, and Korea--you will fly the most fearsome helicopter that has ever been designed against enemies on land, sea, and air.\n\nApache Longbow took flying simulators to the next level. The developers constructed the flight model with fanatical attention to detail, going so far as to bring in Apache pilots to fly the in-game chopper and offer their feedback on how real the experience felt. Every flight simulator enthusiast will be pleased with the complexity and realism this game has to offer. Meanwhile, to make the game more accessible there is also an arcade mode where the flight mechanics aren't nearly as realistic, but there's still tons of fun to be had. So whichever you are - a slow-and-low hardcore sim fan or someone who just likes to fly about and blow things up - this game has something for you.",
        "total_rating": 91.0,
    },
    {
        "id": 654,
        "cover": {
            "id": 116395,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2ht7.jpg",
        },
        "first_release_date": 1158019200,
        "genres": [
            {"id": 11, "name": "Real Time Strategy (RTS)"},
            {"id": 15, "name": "Strategy"},
        ],
        "involved_companies": [
            {"id": 1531, "company": {"id": 197, "name": "THQ"}},
            {"id": 1532, "company": {"id": 196, "name": "Relic Entertainment"}},
            {"id": 18997, "company": {"id": 3991, "name": "Russel"}},
        ],
        "name": "Company of Heroes",
        "similar_games": [
            {"id": 276, "name": "Supreme Commander"},
            {"id": 440, "name": "Medieval II: Total War"},
            {"id": 587, "name": "Act of War: Direct Action"},
            {"id": 617, "name": "Brothers in Arms: Earned in Blood"},
            {"id": 621, "name": "Call of Duty"},
            {"id": 622, "name": "Call of Duty 2"},
            {"id": 649, "name": "Command & Conquer: Generals"},
            {"id": 848, "name": "Rise of Nations"},
            {"id": 5647, "name": "Enemy Front"},
            {"id": 9477, "name": "Soldiers: Heroes of World War II"},
        ],
        "summary": "Command the company that changed the face of history! Battle your way across Europe as your troops make intuitive use of the terrain and buildings for cover and mount attacks on an equally intelligent enemy. Your Mission. Your Men. Your Decisions.",
        "total_rating": 90.30563931285725,
    },
    {
        "id": 657,
        "cover": {
            "id": 272362,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co5u5m.jpg",
        },
        "first_release_date": 1002672000,
        "genres": [{"id": 12, "name": "Role-playing (RPG)"}],
        "involved_companies": [
            {"id": 1536, "company": {"id": 87, "name": "Mythic Entertainment"}}
        ],
        "name": "Dark Age of Camelot",
        "similar_games": [
            {"id": 6, "name": "Baldur's Gate II: Shadows of Amn"},
            {"id": 125, "name": "Diablo"},
            {"id": 660, "name": "Darkstone"},
            {"id": 2480, "name": "Torchlight"},
            {"id": 7027, "name": "SpellForce: The Order of Dawn"},
            {"id": 8747, "name": "Perfect World"},
            {"id": 9938, "name": "Aarklash: Legacy"},
            {"id": 15718, "name": "Silverfall"},
            {"id": 18337, "name": "Dofus"},
            {"id": 70754, "name": "Dark Age of Camelot: Darkness Rising"},
        ],
        "summary": "Dark Age of Camelot is a 3D medieval fantasy MMORPG that combines Arthurian lore, Norse mythology and Irish Celtic legends with a dash of high fantasy. It is set in the period after King Arthur's death and his kingdom has split into three parts which are in a constant state of war with each other. DAoC includes both PvE and RvR combat, players can choose to adventure alone or join groups to get completion of credit in large-scale PvE encounters and for communication purposes in RvR.",
        "total_rating": 94.5488909270523,
    },
    {
        "id": 721,
        "cover": {
            "id": 104240,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co28fk.jpg",
        },
        "first_release_date": 1110240000,
        "genres": [
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 15, "name": "Strategy"},
            {"id": 24, "name": "Tactical"},
        ],
        "involved_companies": [
            {"id": 1648, "company": {"id": 21, "name": "Irrational Games"}},
            {"id": 1649, "company": {"id": 668, "name": "Digital Jesters"}},
            {"id": 2182, "company": {"id": 1, "name": "Electronic Arts"}},
        ],
        "name": "Freedom Force vs. The 3rd Reich",
        "similar_games": [
            {"id": 13196, "name": "Tears of Avia"},
            {"id": 25311, "name": "Star Control: Origins"},
            {"id": 36258, "name": "Order of Battle: World War II"},
            {"id": 102057, "name": "Age of Wonders: Planetfall"},
            {"id": 103232, "name": "Super Seducer 2"},
            {"id": 107218, "name": "Desperados III"},
            {"id": 109339, "name": "CHANGE: A Homeless Survival Experience"},
            {"id": 113402, "name": "Dungeon Of Dragon Knight"},
            {"id": 119171, "name": "Baldur's Gate 3"},
            {"id": 119598, "name": 'Tactics V: "Obsidian Brigade"'},
        ],
        "summary": "Freedom is threatened yet again and only Minute Man and his heroic Freedom Force can save the day in the follow up to one of the most critically acclaimed games of 2002.\n\nFreedom Force vs. the Third Reich brings dynamic storytelling, fast-paced tactical role-play, and larger-than-life characters from the comic book pages to the computer screen. In this title, the league of heroes must travel back in time to defeat Blitzkrieg, defender of the Reich and his homicidal henchmen. With action spanning from the blasted battlefields of World War II to the dazzling depths of distant dimensions, Freedom Force vs. the Third Reich will give Freedom Fans more than they can handle.",
        "total_rating": 93.0340874798499,
    },
    {
        "id": 730,
        "cover": {
            "id": 120932,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2lb8.jpg",
        },
        "first_release_date": 1003708800,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 10, "name": "Racing"},
            {"id": 13, "name": "Simulator"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 7700, "company": {"id": 536, "name": "DMA Design"}},
            {"id": 7701, "company": {"id": 29, "name": "Rockstar Games"}},
            {"id": 20012, "company": {"id": 139, "name": "Take-Two Interactive"}},
            {"id": 63952, "company": {"id": 307, "name": "Rockstar Vienna"}},
        ],
        "name": "Grand Theft Auto III",
        "similar_games": [
            {"id": 39, "name": "Mafia"},
            {"id": 731, "name": "Grand Theft Auto IV"},
            {"id": 732, "name": "Grand Theft Auto: San Andreas"},
            {"id": 733, "name": "Grand Theft Auto: Vice City"},
            {"id": 819, "name": "Grand Theft Auto 2"},
            {"id": 980, "name": "Grand Theft Auto"},
            {"id": 1020, "name": "Grand Theft Auto V"},
            {"id": 1121, "name": "Watch_Dogs"},
            {"id": 3262, "name": "Grand Theft Auto: Vice City Stories"},
            {"id": 19441, "name": "Watch Dogs 2"},
        ],
        "summary": "Featuring a fully 3-D living city, a combination of narrative driven and non-linear gameplay and a completely open environment, Grand Theft Auto III represents a huge leap forward in interactive entertainment. For the first time, players are put at the heart of their very own gangster movie, and let loose in a fully-realised 3 dimensional city, in which anything can happen and probably will.\n\nWith a cast of hundreds, 50 plus vehicles, ranging from sports cars to ice cream trucks and from boats to buses, 3 hours of music, including opera, reggae, house, drum and bass, pop and disco, a huge array of street ready weapons and some of the seediest characters in video game history, Grand Theft Auto 3 is a sprawling epic which will show you that sometimes, crime can pay and sometimes it can pay you back. Available now for PlayStation2, Xbox, PC and Macintosh.",
        "total_rating": 90.09842401023576,
    },
    {
        "id": 732,
        "cover": {
            "id": 120933,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2lb9.jpg",
        },
        "first_release_date": 1098748800,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 10, "name": "Racing"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 55974, "company": {"id": 29, "name": "Rockstar Games"}},
            {"id": 55979, "company": {"id": 365, "name": "Rockstar North"}},
            {"id": 55980, "company": {"id": 139, "name": "Take-Two Interactive"}},
        ],
        "name": "Grand Theft Auto: San Andreas",
        "similar_games": [
            {"id": 564, "name": "Rogue Warrior"},
            {"id": 730, "name": "Grand Theft Auto III"},
            {"id": 731, "name": "Grand Theft Auto IV"},
            {"id": 733, "name": "Grand Theft Auto: Vice City"},
            {"id": 1020, "name": "Grand Theft Auto V"},
            {"id": 1121, "name": "Watch_Dogs"},
            {"id": 3262, "name": "Grand Theft Auto: Vice City Stories"},
            {"id": 3263, "name": "Grand Theft Auto: Liberty City Stories"},
            {"id": 3270, "name": "Grand Theft Auto: Chinatown Wars"},
            {"id": 19441, "name": "Watch Dogs 2"},
        ],
        "summary": "Returning after his mother's murder to the semi-fictional city of Los Santos (based on Los Angeles), Carl Johnson, a former gang banger, must take back the streets for his family and friends by gaining respect and once again gaining control over the streets. However, a story filled with crime, lies and corruption will lead him to trudge the entire state of San Andreas (based on California and Nevada) to rebuild his life.",
        "total_rating": 91.85683311147571,
    },
    {
        "id": 733,
        "cover": {
            "id": 120935,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2lbb.jpg",
        },
        "first_release_date": 1035676800,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 10, "name": "Racing"},
            {"id": 31, "name": "Adventure"},
            {"id": 33, "name": "Arcade"},
        ],
        "involved_companies": [
            {"id": 8285, "company": {"id": 29, "name": "Rockstar Games"}},
            {"id": 20013, "company": {"id": 139, "name": "Take-Two Interactive"}},
            {"id": 63950, "company": {"id": 365, "name": "Rockstar North"}},
            {"id": 63951, "company": {"id": 307, "name": "Rockstar Vienna"}},
        ],
        "name": "Grand Theft Auto: Vice City",
        "similar_games": [
            {"id": 40, "name": "Mafia II"},
            {"id": 730, "name": "Grand Theft Auto III"},
            {"id": 731, "name": "Grand Theft Auto IV"},
            {"id": 732, "name": "Grand Theft Auto: San Andreas"},
            {"id": 1020, "name": "Grand Theft Auto V"},
            {"id": 1121, "name": "Watch_Dogs"},
            {"id": 3262, "name": "Grand Theft Auto: Vice City Stories"},
            {"id": 3263, "name": "Grand Theft Auto: Liberty City Stories"},
            {"id": 3270, "name": "Grand Theft Auto: Chinatown Wars"},
            {"id": 19441, "name": "Watch Dogs 2"},
        ],
        "summary": "In the year 1986, Tommy Vercetti is heavily indebted to his mafia superiors after a drug deal gone awry, but his dreams of taking over Vice City (based on Miami) push him down a different path. Featuring a wide variety of vehicles and weapons, radio stations playing hit songs from the era and an intense atmosphere, GTA: Vice City is an open-world sandbox satire of '80's Miami.",
        "total_rating": 90.91426604703075,
    },
    {
        "id": 796,
        "cover": {
            "id": 156994,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co3d4y.jpg",
        },
        "first_release_date": 1109030400,
        "genres": [{"id": 14, "name": "Sport"}],
        "involved_companies": [
            {"id": 1781, "company": {"id": 1, "name": "Electronic Arts"}},
            {"id": 2326, "company": {"id": 277, "name": "EA Canada"}},
        ],
        "name": "MVP Baseball 2005",
        "similar_games": [
            {"id": 37952, "name": "Koushien 3"},
            {"id": 61401, "name": "The Baseball 2003"},
            {"id": 94110, "name": "World Series Baseball"},
            {"id": 102122, "name": "Madden NFL 19"},
            {"id": 111654, "name": "MLB The Show 19"},
            {"id": 114286, "name": "Madden NFL 20"},
            {"id": 114287, "name": "FIFA 20"},
            {"id": 116352, "name": "Real Football 2018"},
            {"id": 116353, "name": "Real Football 2019"},
            {"id": 136734, "name": "Jikkyou Powerful Pro Yakyuu 6"},
        ],
        "summary": "MVP Baseball 2005 is a baseball video game developed and published by Electronic Arts. It features then-Boston Red Sox left fielder Manny Ramirez on its cover. The game features full Major League Baseball, Minor League Baseball, and Major League Baseball Players Association licenses. It holds the 98th spot on IGN's reader's choice top 100 games ever as of 2006. As with previous versions of the game, the announcers are Duane Kuiper and Mike Krukow, real-life announcers for the San Francisco Giants.",
        "total_rating": 91.87733105655965,
    },
    {
        "id": 804,
        "cover": {
            "id": 117125,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2idh.jpg",
        },
        "first_release_date": 1045094400,
        "genres": [
            {"id": 10, "name": "Racing"},
            {"id": 13, "name": "Simulator"},
            {"id": 14, "name": "Sport"},
        ],
        "involved_companies": [
            {"id": 1794, "company": {"id": 24, "name": "Sierra Entertainment"}},
            {"id": 1795, "company": {"id": 670, "name": "Papyrus Design Group"}},
            {"id": 2256, "company": {"id": 73, "name": "Aspyr Media"}},
        ],
        "name": "NASCAR Racing 2003 Season",
        "similar_games": [
            {"id": 96, "name": "Need for Speed: Underground"},
            {"id": 97, "name": "Need for Speed: Underground 2"},
            {"id": 100, "name": "Need for Speed: ProStreet"},
            {"id": 642, "name": "Colin McRae Rally 2.0"},
            {"id": 803, "name": "NASCAR Racing 2002 Season"},
            {"id": 3772, "name": "Wreckfest"},
            {"id": 5943, "name": "NASCAR 06: Total Team Control"},
            {"id": 5944, "name": "NASCAR 07"},
            {"id": 5947, "name": "NASCAR Thunder 2004"},
            {"id": 72390, "name": "Mercedes-Benz Truck Racing"},
        ],
        "summary": "The latest release from this series since 1999. \n \n23 real-life tracks (including the new versions of New Hampshire International Speedway and Infineon Raceway) are included. The game has been reworked with an improved graphics and physics engine, developed in partnership with Goodyear Tire & Rubber Company and Jasper Motorsports. Tutorials will bring the player up to speed quickly, while driving aids will help them compete against NASCAR pros. An adaptive AI will keep the game challenging at all skill levels. \n \nMultiplayer supports up to 42 players online in the same race.",
        "total_rating": 100.0,
    },
    {
        "id": 863,
        "cover": {
            "id": 182345,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co3wp5.jpg",
        },
        "first_release_date": 918777600,
        "genres": [
            {"id": 13, "name": "Simulator"},
            {"id": 15, "name": "Strategy"},
            {"id": 16, "name": "Turn-based strategy (TBS)"},
        ],
        "involved_companies": [
            {"id": 1892, "company": {"id": 1, "name": "Electronic Arts"}},
            {"id": 1893, "company": {"id": 377, "name": "Firaxis Games"}},
            {"id": 2324, "company": {"id": 73, "name": "Aspyr Media"}},
            {"id": 2325, "company": {"id": 106, "name": "Loki Software"}},
        ],
        "name": "Sid Meier's Alpha Centauri",
        "similar_games": [
            {"id": 3700, "name": "The Settlers: Rise of an Empire"},
            {"id": 9197, "name": "Sid Meier's Alien Crossfire"},
            {"id": 9789, "name": "RimWorld"},
            {"id": 10345, "name": "Galactic Civilizations III"},
            {"id": 11550, "name": "Endless Space 2"},
            {"id": 11582, "name": "Stellaris"},
            {"id": 13200, "name": "Planetbase"},
            {"id": 17130, "name": "Unclaimed World"},
            {"id": 19301, "name": "The Long Journey Home"},
            {"id": 33153, "name": "Judgment: Apocalypse Survival Simulation"},
        ],
        "summary": "Legendary designer Sid Meier presents the next evolution in strategy games, with the most addictive, compelling gameplay yet. Explore the alien planet that is your new home and uncover its myriad mysteries. Discover over 75 extraordinary technologies. Build over 60 base upgrades and large scales secret projects for your empire. Conquer your enemies with a war machine that you design from over 32,000 possible unit types.",
        "total_rating": 90.7095092197238,
    },
    {
        "id": 902,
        "cover": {
            "id": 91077,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1y9x.jpg",
        },
        "first_release_date": 662688000,
        "genres": [
            {"id": 15, "name": "Strategy"},
            {"id": 16, "name": "Turn-based strategy (TBS)"},
        ],
        "involved_companies": [
            {"id": 1955, "company": {"id": 152, "name": "MicroProse"}},
            {"id": 5001, "company": {"id": 630, "name": "Koei"}},
        ],
        "name": "Sid Meier's Civilization",
        "similar_games": [
            {"id": 634, "name": "Sid Meier's Civilization II"},
            {"id": 7615, "name": "Might & Magic Heroes VII"},
            {"id": 13196, "name": "Tears of Avia"},
            {"id": 13660, "name": "StarDrive 2"},
            {"id": 17111, "name": "Imagine Earth"},
            {"id": 32510, "name": "Cthulhu Realms"},
            {"id": 36258, "name": "Order of Battle: World War II"},
            {"id": 102057, "name": "Age of Wonders: Planetfall"},
            {"id": 117417, "name": "Clans to Kingdoms"},
            {"id": 128422, "name": "Royals"},
        ],
        "summary": "Sid Meier's Civilization is a turn-based strategy computer game created by Sid Meier for MicroProse in 1991.The game's objective is \"...to build an empire that would stand the test of time\". The game begins in 4000 BC, and the players attempt to expand and develop their empires through the ages until modern and near-future times. It is also known simply as Civilization.",
        "total_rating": 93.38052244059699,
    },
    {
        "id": 916,
        "cover": {
            "id": 114058,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2g0a.jpg",
        },
        "first_release_date": 849312000,
        "genres": [
            {"id": 2, "name": "Point-and-click"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {
                "id": 3440,
                "company": {
                    "id": 141,
                    "name": "Virgin Interactive Entertainment (Europe) Ltd.",
                },
            },
            {"id": 3441, "company": {"id": 602, "name": "Burst Studios"}},
        ],
        "name": "Toonstruck",
        "similar_games": [
            {"id": 8983, "name": "Obduction"},
            {"id": 9112, "name": "The Book of Unwritten Tales 2"},
            {"id": 9938, "name": "Aarklash: Legacy"},
            {"id": 10388, "name": "Legends of Eisenwald"},
            {"id": 15409, "name": "Folk Tale"},
            {"id": 16992, "name": "Human: Fall Flat"},
            {"id": 18841, "name": "Gibbous - A Cthulhu Adventure"},
            {"id": 22387, "name": "Legrand Legacy"},
            {"id": 56033, "name": "Dream Alone"},
            {"id": 72373, "name": "Getting Over It with Bennett Foddy"},
        ],
        "summary": 'Toonstruck is an adventure game released in 1996 in which, although all the imagery is drawn and scanned into the game, the protagonist Drew Blanc (played and voiced by Christopher Lloyd) is an actual video-captured representation of the actor (the name is a pun, since the character has "drawn a blank" on coming up with a new idea for a character). Drew\'s sidekick, crudely named Flux Wildly, is a drawn character voiced by Dan Castellaneta. Toonstruck also features scan-line compressed FMV and was also one of the first video games to include stock music from APM Music, notably the classic "Spooky Scherzo" by Sam Fonteyn and "Lonely Hearts Club A" by David Bell.',
        "total_rating": 90.78573377016158,
    },
    {
        "id": 999,
        "cover": {
            "id": 91026,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1y8i.jpg",
        },
        "first_release_date": 874540800,
        "genres": [
            {"id": 8, "name": "Platform"},
            {"id": 9, "name": "Puzzle"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 178220, "company": {"id": 727, "name": "Oddworld Inhabitants"}},
            {"id": 178224, "company": {"id": 205, "name": "GT Interactive"}},
            {"id": 178225, "company": {"id": 727, "name": "Oddworld Inhabitants"}},
            {"id": 178226, "company": {"id": 311, "name": "Digital Dialect"}},
        ],
        "name": "Oddworld: Abe's Oddysee",
        "similar_games": [
            {"id": 533, "name": "Dishonored"},
            {"id": 1000, "name": "Oddworld: Abe's Exoddus"},
            {"id": 1341, "name": "Beyond Good & Evil"},
            {"id": 2939, "name": "The Vanishing of Ethan Carter"},
            {"id": 3025, "name": "Middle-earth: Shadow of Mordor"},
            {"id": 3225, "name": "No Man's Sky"},
            {"id": 7342, "name": "INSIDE"},
            {"id": 7386, "name": "The Talos Principle"},
            {"id": 11646, "name": "Ziggurat"},
            {"id": 16992, "name": "Human: Fall Flat"},
        ],
        "summary": "Oddworld: Abe's Oddysee is the first game set in the fictional Oddworld universe. It is a platformer with puzzle-solving elements, focusing on the portrayal of a weak, underpowered character in a grim and hostile world, who has to rely on his cunning to outwit enemies and overcome hazards. The game has pre-rendered background graphics and uses CG movies of similar style to advance the story between the levels.\n\nThe main character Abe is almost completely helpless: he cannot use weapons and is usually instantly killed by his brutal enemies if he confronts them directly. For this reason, most of the game involves careful exploration, timed movement, sneaking, and outsmarting the foes through various means: throwing stones to confuse them, luring them into traps, etc. Abe can run, jump, climb, tiptoe, crouch, and roll; in most areas these actions are essential to his survival. A few stages involve Abe riding a large animal known as Elum.\n\nAbe's only special power is chanting, which he can use to stun certain enemies for a while or possess them. When Abe possess an enemy he gains his abilities: for example, possessing the body or a ferocious Slig allows the player to shoot from his machine gun, communicate with other creatures of his kind, and even commit suicide, clearing the way for Abe.",
        "total_rating": 91.20139918128255,
    },
    {
        "id": 1009,
        "cover": {
            "id": 81915,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co1r7f.jpg",
        },
        "first_release_date": 1371168000,
        "genres": [{"id": 5, "name": "Shooter"}, {"id": 31, "name": "Adventure"}],
        "involved_companies": [
            {"id": 73932, "company": {"id": 401, "name": "Naughty Dog"}},
            {
                "id": 185895,
                "company": {"id": 13634, "name": "Sony Computer Entertainment"},
            },
        ],
        "name": "The Last of Us",
        "similar_games": [
            {"id": 533, "name": "Dishonored"},
            {"id": 538, "name": "BioShock Infinite"},
            {"id": 1020, "name": "Grand Theft Auto V"},
            {"id": 1121, "name": "Watch_Dogs"},
            {"id": 1164, "name": "Tomb Raider"},
            {"id": 1985, "name": "Metal Gear Solid V: The Phantom Pain"},
            {"id": 2031, "name": "Wolfenstein: The New Order"},
            {"id": 3042, "name": "Dying Light"},
            {"id": 11270, "name": "The Cat Lady"},
            {"id": 19441, "name": "Watch Dogs 2"},
        ],
        "summary": "A third person shooter/stealth/survival hybrid, in which twenty years after the outbreak of a parasitic fungus which takes over the neural functions of humans, Joel, a Texan with a tragic familial past, finds himself responsible with smuggling a fourteen year old girl named Ellie to a militia group called the Fireflies, while avoiding strict and deadly authorities, infected fungal hosts and other violent survivors.",
        "total_rating": 92.47678737150184,
    },
    {
        "id": 1026,
        "cover": {
            "id": 181427,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co3vzn.jpg",
        },
        "first_release_date": 690681600,
        "genres": [
            {"id": 9, "name": "Puzzle"},
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 101094, "company": {"id": 25230, "name": "St. GIGA"}},
            {"id": 129705, "company": {"id": 70, "name": "Nintendo"}},
            {"id": 162318, "company": {"id": 421, "name": "Nintendo EAD"}},
            {"id": 162319, "company": {"id": 70, "name": "Nintendo"}},
        ],
        "name": "The Legend of Zelda: A Link to the Past",
        "similar_games": [
            {"id": 533, "name": "Dishonored"},
            {"id": 832, "name": "Planescape: Torment"},
            {"id": 1028, "name": "The Legend of Zelda: Link's Awakening"},
            {"id": 1029, "name": "The Legend of Zelda: Ocarina of Time"},
            {"id": 1032, "name": "The Legend of Zelda: Oracle of Seasons"},
            {"id": 1035, "name": "The Legend of Zelda: The Minish Cap"},
            {"id": 1036, "name": "The Legend of Zelda: Twilight Princess"},
            {"id": 1037, "name": "The Legend of Zelda: Phantom Hourglass"},
            {"id": 1041, "name": "The Legend of Zelda: Oracle of Ages"},
            {"id": 11763, "name": "Sokoban"},
        ],
        "summary": "A top-down action/adventure title in which Link, a blacksmith's nephew living in the fantastical land of Hyrule, must free the land from the evildoings of Ganon by taking up the mythical Master Sword and collecting the three Triforces in order to free the Seven Maidens, including the princess of Hyrule, Zelda, from the dungeons and castles of the Dark World.",
        "total_rating": 96.1509010670479,
    },
    {
        "id": 1029,
        "cover": {
            "id": 170637,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co3nnx.jpg",
        },
        "first_release_date": 911606400,
        "genres": [
            {"id": 9, "name": "Puzzle"},
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 167533, "company": {"id": 70, "name": "Nintendo"}},
            {"id": 167534, "company": {"id": 421, "name": "Nintendo EAD"}},
        ],
        "name": "The Legend of Zelda: Ocarina of Time",
        "similar_games": [
            {"id": 121, "name": "Minecraft"},
            {"id": 533, "name": "Dishonored"},
            {"id": 1026, "name": "The Legend of Zelda: A Link to the Past"},
            {"id": 1032, "name": "The Legend of Zelda: Oracle of Seasons"},
            {"id": 1035, "name": "The Legend of Zelda: The Minish Cap"},
            {"id": 1036, "name": "The Legend of Zelda: Twilight Princess"},
            {"id": 1037, "name": "The Legend of Zelda: Phantom Hourglass"},
            {"id": 1041, "name": "The Legend of Zelda: Oracle of Ages"},
            {"id": 2909, "name": "The Legend of Zelda: A Link Between Worlds"},
            {"id": 7346, "name": "The Legend of Zelda: Breath of the Wild"},
        ],
        "summary": "A 3D reimagining of the core premise of The Legend of Zelda: A Link to the Past (1991), Ocarina of Time follows Link, the protagonist, as he picks up a sword and leaves behind his humble origins in order to trek across the land of Hyrule, venture into its treacherous dungeons and travel through time itself to fulfill his destiny as the Hero of Time by defeating his enemy Ganondorf and ridding Hyrule of evil.",
        "total_rating": 91.758681172588,
    },
    {
        "id": 1036,
        "cover": {
            "id": 169555,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co3mtv.jpg",
        },
        "first_release_date": 1163894400,
        "genres": [
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 167545, "company": {"id": 70, "name": "Nintendo"}},
            {"id": 167546, "company": {"id": 1366, "name": "Nintendo EAD Group No. 3"}},
        ],
        "name": "The Legend of Zelda: Twilight Princess",
        "similar_games": [
            {"id": 121, "name": "Minecraft"},
            {"id": 472, "name": "The Elder Scrolls V: Skyrim"},
            {"id": 533, "name": "Dishonored"},
            {"id": 832, "name": "Planescape: Torment"},
            {"id": 1026, "name": "The Legend of Zelda: A Link to the Past"},
            {"id": 1029, "name": "The Legend of Zelda: Ocarina of Time"},
            {"id": 1032, "name": "The Legend of Zelda: Oracle of Seasons"},
            {"id": 1035, "name": "The Legend of Zelda: The Minish Cap"},
            {"id": 1037, "name": "The Legend of Zelda: Phantom Hourglass"},
            {"id": 7346, "name": "The Legend of Zelda: Breath of the Wild"},
        ],
        "summary": "Link, a young man raised as a wrangler in a small, rural village, is ordered by the mayor to attend the Hyrule Summit. He sets off, oblivious to the dark fate that has descended upon the kingdom. When he enters the Twilight Realm that has covered Hyrule, he transforms into a wolf and is captured. A mysterious figure named Midna helps him break free, and with the aid of her magic, they set off to free the land from the shadows. Link must explore the vast land of Hyrule and uncover the mystery behind its plunge into darkness.\n\nFor Nintendo's long-awaited Legend of Zelda: Twilight Princess, the designers have split the game into two versions -- one for GameCube, and one specially designed to make use of the Wii utilizing the powers of the Wii controller for all-new ways of exploring Hyrule.",
        "total_rating": 90.86890637595505,
    },
    {
        "id": 1039,
        "cover": {
            "id": 171926,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co3onq.jpg",
        },
        "first_release_date": 1308182400,
        "genres": [
            {"id": 8, "name": "Platform"},
            {"id": 9, "name": "Puzzle"},
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 2480, "company": {"id": 421, "name": "Nintendo EAD"}},
            {"id": 2481, "company": {"id": 739, "name": "GREZZO"}},
            {"id": 2482, "company": {"id": 70, "name": "Nintendo"}},
        ],
        "name": "The Legend of Zelda: Ocarina of Time 3D",
        "similar_games": [
            {"id": 28070, "name": "Planet Alpha"},
            {"id": 55199, "name": "Dragon: Marked for Death"},
            {"id": 68582, "name": "Dark Devotion"},
            {"id": 81249, "name": "The Elder Scrolls VI"},
            {"id": 96217, "name": "Eternity: The Last Unicorn"},
            {"id": 101608, "name": "Anima: Gate of Memories - The Nameless Chronicles"},
            {"id": 103303, "name": "The Elder Scrolls: Blades"},
            {"id": 105049, "name": "Remnant: From the Ashes"},
            {"id": 106987, "name": "Torchlight III"},
            {"id": 110503, "name": "Degrees of Separation"},
        ],
        "summary": "A Nintendo 3DS remaster of The Legend of Zelda: Ocarina of Time (1998), originally for the Nintendo 64, with more up-to-date graphics, streamlined UI, alternative aiming controls, different additional game modes and difficulty tweaks.",
        "total_rating": 91.61212459207499,
    },
    {
        "id": 1041,
        "cover": {
            "id": 132049,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2tw1.jpg",
        },
        "first_release_date": 983232000,
        "genres": [
            {"id": 12, "name": "Role-playing (RPG)"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 130354, "company": {"id": 70, "name": "Nintendo"}},
            {"id": 171309, "company": {"id": 41283, "name": "Flagship"}},
        ],
        "name": "The Legend of Zelda: Oracle of Ages",
        "similar_games": [
            {"id": 1025, "name": "Zelda II: The Adventure of Link"},
            {"id": 1026, "name": "The Legend of Zelda: A Link to the Past"},
            {"id": 1028, "name": "The Legend of Zelda: Link's Awakening"},
            {"id": 1029, "name": "The Legend of Zelda: Ocarina of Time"},
            {"id": 1032, "name": "The Legend of Zelda: Oracle of Seasons"},
            {"id": 1035, "name": "The Legend of Zelda: The Minish Cap"},
            {"id": 1036, "name": "The Legend of Zelda: Twilight Princess"},
            {"id": 1037, "name": "The Legend of Zelda: Phantom Hourglass"},
            {"id": 2909, "name": "The Legend of Zelda: A Link Between Worlds"},
            {"id": 7346, "name": "The Legend of Zelda: Breath of the Wild"},
        ],
        "summary": "The Legend of Zelda: Oracle of Ages and The Legend of Zelda: Oracle of Seasons represent the pinnacle of classic 2D Zelda gameplay.\n\nWhen played together, these two games offer an ultimate adventure not possible when each game is experienced on its own. The games feature a link system that unlocks access to additional content that you can't access any other way.",
        "total_rating": 90.037419406829,
    },
    {
        "id": 1046,
        "cover": {
            "id": 110505,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2d9l.jpg",
        },
        "first_release_date": 721958400,
        "genres": [
            {"id": 13, "name": "Simulator"},
            {"id": 15, "name": "Strategy"},
            {"id": 31, "name": "Adventure"},
            {"id": 32, "name": "Indie"},
        ],
        "involved_companies": [
            {"id": 2495, "company": {"id": 741, "name": "Toys for Bob"}},
            {"id": 2500, "company": {"id": 547, "name": "Accolade"}},
        ],
        "name": "Star Control II",
        "similar_games": [
            {"id": 17130, "name": "Unclaimed World"},
            {"id": 25311, "name": "Star Control: Origins"},
            {"id": 26574, "name": "Force of Nature"},
            {"id": 35994, "name": "Survivalist"},
            {"id": 36553, "name": "Medieval Kingdom Wars"},
            {"id": 78550, "name": "Bad North"},
            {"id": 79134, "name": "Ancient Cities"},
            {"id": 105269, "name": "Gene Rain"},
            {"id": 109339, "name": "CHANGE: A Homeless Survival Experience"},
            {"id": 111130, "name": "Apsulov: End of Gods"},
        ],
        "summary": "Star Control II, the sequel to the original Star Control, is a space adventure game that features role-playing elements alongside a 2D space ship melee combat system. The player assumes the role of The Captain of a single starship wandering a detailed environment of solar systems, gradually gathering information and resources in order to defeat a mysterious and implacable enemy.",
        "total_rating": 95.93253478956188,
    },
    {
        "id": 1070,
        "cover": {
            "id": 133702,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2v5y.jpg",
        },
        "first_release_date": 659145600,
        "genres": [{"id": 8, "name": "Platform"}, {"id": 31, "name": "Adventure"}],
        "involved_companies": [
            {"id": 164873, "company": {"id": 70, "name": "Nintendo"}},
            {"id": 164874, "company": {"id": 421, "name": "Nintendo EAD"}},
        ],
        "name": "Super Mario World",
        "similar_games": [
            {"id": 1741, "name": "Mega Man X"},
            {"id": 19150, "name": "Vagante"},
            {"id": 20329, "name": "Figment"},
            {"id": 22387, "name": "Legrand Legacy"},
            {"id": 28070, "name": "Planet Alpha"},
            {"id": 36198, "name": "Children of Morta"},
            {"id": 55173, "name": "Semblance"},
            {"id": 55190, "name": "Pikuniku"},
            {"id": 56033, "name": "Dream Alone"},
            {"id": 96217, "name": "Eternity: The Last Unicorn"},
        ],
        "summary": "A 2D platformer and first entry on the SNES in the Super Mario franchise, Super Mario World follows Mario as he attempts to defeat Bowser's underlings and rescue Princess Peach from his clutches. The game features a save system, a less linear world map, an expanded movement arsenal and numerous new items for Mario, alongside new approaches to level design and art direction.",
        "total_rating": 96.4498295011965,
    },
    {
        "id": 1073,
        "cover": {
            "id": 120069,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co2kn9.jpg",
        },
        "first_release_date": 807580800,
        "genres": [{"id": 8, "name": "Platform"}, {"id": 31, "name": "Adventure"}],
        "involved_companies": [
            {"id": 155520, "company": {"id": 25230, "name": "St. GIGA"}},
            {"id": 162314, "company": {"id": 421, "name": "Nintendo EAD"}},
            {"id": 162315, "company": {"id": 70, "name": "Nintendo"}},
        ],
        "name": "Super Mario World 2: Yoshi's Island",
        "similar_games": [
            {"id": 19150, "name": "Vagante"},
            {"id": 20342, "name": "Toby: The Secret Mine"},
            {"id": 24426, "name": "Forgotton Anne"},
            {"id": 28070, "name": "Planet Alpha"},
            {"id": 37001, "name": "Ori and the Will of the Wisps"},
            {"id": 55190, "name": "Pikuniku"},
            {"id": 96217, "name": "Eternity: The Last Unicorn"},
            {"id": 106987, "name": "Torchlight III"},
            {"id": 110503, "name": "Degrees of Separation"},
            {"id": 113360, "name": "Hytale"},
        ],
        "summary": "Super Mario World 2: Yoshi's Island is a platform video game acting as a prequel to 1990's Super Mario World. The game casts players as Yoshi as he escorts Baby Mario through 48 levels in order to reunite him with his brother Luigi, who had been kidnapped by Baby Bowser's minions. As a Super Mario series platformer, Yoshi runs and jumps to reach the end of the level while solving puzzles and collecting items. In a style new to the series, the game has a hand-drawn aesthetic and is the first to have Yoshi as its main character. The game introduces his signature abilities to flutter jump, produce eggs from swallowed enemies, and transform into vehicles.",
        "total_rating": 94.3370361671596,
    },
    {
        "id": 1077,
        "cover": {
            "id": 95604,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co21ro.jpg",
        },
        "first_release_date": 1193875200,
        "genres": [{"id": 8, "name": "Platform"}, {"id": 31, "name": "Adventure"}],
        "involved_companies": [
            {"id": 98645, "company": {"id": 421, "name": "Nintendo EAD"}},
            {"id": 98646, "company": {"id": 70, "name": "Nintendo"}},
        ],
        "name": "Super Mario Galaxy",
        "similar_games": [
            {"id": 1068, "name": "Super Mario Bros. 3"},
            {"id": 1074, "name": "Super Mario 64"},
            {"id": 1078, "name": "Super Mario Galaxy 2"},
            {"id": 2180, "name": "Super Mario 3D World"},
            {"id": 2183, "name": "Mario Kart Wii"},
            {"id": 2350, "name": "Mario Kart 8"},
            {"id": 24426, "name": "Forgotton Anne"},
            {"id": 55190, "name": "Pikuniku"},
            {"id": 81145, "name": "Mario Tennis Aces"},
            {"id": 115276, "name": "Super Mario Maker 2"},
        ],
        "summary": "A 3D platformer and first Wii entry in the Super Mario franchise, Super Mario Galaxy sees Mario jump across planets and galaxies with varying items, enemies, geographies and gravity mechanics in order to reach his enemy Bowser, who has attacked the Mushroom Kingdom and hijacked Princess Peach's castle with her inside.",
        "total_rating": 93.70266752644655,
    },
    {
        "id": 1078,
        "cover": {
            "id": 95673,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co21tl.jpg",
        },
        "first_release_date": 1274572800,
        "genres": [{"id": 8, "name": "Platform"}, {"id": 31, "name": "Adventure"}],
        "involved_companies": [
            {"id": 98647, "company": {"id": 70, "name": "Nintendo"}},
            {"id": 98648, "company": {"id": 421, "name": "Nintendo EAD"}},
            {"id": 129636, "company": {"id": 70, "name": "Nintendo"}},
        ],
        "name": "Super Mario Galaxy 2",
        "similar_games": [
            {"id": 358, "name": "Super Mario Bros."},
            {"id": 843, "name": "Rayman 2: The Great Escape"},
            {"id": 1036, "name": "The Legend of Zelda: Twilight Princess"},
            {"id": 1068, "name": "Super Mario Bros. 3"},
            {"id": 1075, "name": "Super Mario Sunshine"},
            {"id": 1079, "name": "Super Mario 3D Land"},
            {"id": 2180, "name": "Super Mario 3D World"},
            {"id": 3349, "name": "Paper Mario: The Thousand-Year Door"},
            {"id": 3363, "name": "Mario & Luigi: Bowser's Inside Story"},
            {"id": 26758, "name": "Super Mario Odyssey"},
        ],
        "summary": "Super Mario Galaxy 2 is the sequel to Super Mario Galaxy and the fourth 3D platformer entry in the Mario franchise. The sequel retains many elements from its predecessor, such as the adventure being in outer space, the element of gravity, and recurring objects such as Launch Stars and Sling Stars. Returning items include the Bee Mushroom and the Fire Flower. However, the game introduces new elements as well, such as the utilization of Yoshi, new power-ups like the Cloud Flower, and the use of a guide within the game for beginner players.",
        "total_rating": 92.56187894161755,
    },
    {
        "id": 1103,
        "cover": {
            "id": 265426,
            "url": "//images.igdb.com/igdb/image/upload/t_thumb/co5osy.jpg",
        },
        "first_release_date": 764035200,
        "genres": [
            {"id": 5, "name": "Shooter"},
            {"id": 8, "name": "Platform"},
            {"id": 31, "name": "Adventure"},
        ],
        "involved_companies": [
            {"id": 180279, "company": {"id": 1809, "name": "Nintendo R&D1"}},
            {"id": 180281, "company": {"id": 25077, "name": "Intelligent Systems"}},
            {"id": 189879, "company": {"id": 70, "name": "Nintendo"}},
            {"id": 189880, "company": {"id": 70, "name": "Nintendo"}},
        ],
        "name": "Super Metroid",
        "similar_games": [
            {"id": 1006, "name": "Syndicate"},
            {"id": 1026, "name": "The Legend of Zelda: A Link to the Past"},
            {"id": 1101, "name": "Metroid"},
            {"id": 3019, "name": "Starbound"},
            {"id": 3222, "name": "Chasm"},
            {"id": 7344, "name": "Ori and the Blind Forest"},
            {"id": 7406, "name": "Aquaria"},
            {"id": 8652, "name": "Axiom Verge"},
            {"id": 14593, "name": "Hollow Knight"},
            {"id": 26855, "name": "Dead Cells"},
        ],
        "summary": "The Space Pirates, merciless agents of the evil Mother Brain, have stolen the last Metroid from a research station, and once again Mother Brain threatens the safety of the galaxy! Samus Aran must don her awesome array of high-tech weaponry to retrieve the deadly Metroid hidden deep within the cave-riddled planet Zebes. Super Metroid features excellent graphics, with a huge variety of enemies and worlds to explore. The side-view action will be familiar to many players, only now there are new weapons and items, including the Grappling Beam, which allows Samus to swing across large chasms, and the X-Ray Scope, which reveals secret passages.",
        "total_rating": 96.5034614858202,
    },
]
